-- ==========================================
-- SCHEMA PRODUCTION - TLC Logística
-- ==========================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ==========================================
-- 2. TABLES
-- ==========================================

-- 2.1 BUSINESS SETTINGS
CREATE TABLE IF NOT EXISTS public.business (
    id int PRIMARY KEY DEFAULT 1,
    business_name text,
    vapid_public_key text,
    push_vapid_key text,
    created_at timestamptz DEFAULT now()
);

-- 2.2 NOTIFICATIONS
CREATE TABLE IF NOT EXISTS public.notifications (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at timestamptz DEFAULT now(),
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    contact_id uuid,
    title text NOT NULL,
    body text NOT NULL,
    read boolean DEFAULT false,
    data jsonb DEFAULT '{}'::jsonb
);

-- 2.3 PUSH SUBSCRIPTIONS
CREATE TABLE IF NOT EXISTS public.push_subscriptions (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at timestamptz DEFAULT now(),
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    endpoint text NOT NULL,
    keys jsonb NOT NULL,
    CONSTRAINT push_subscriptions_user_endpoint_key UNIQUE(user_id, endpoint)
);

-- 2.4 COLLABORATORS (Mirror of auth.users with extra info)
CREATE TABLE IF NOT EXISTS public.collaborators (
    id uuid REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    created_at timestamptz DEFAULT now(),
    name text,
    email text,
    phone text,
    matricula text,
    status text DEFAULT 'activo', -- activo, inactivo
    commission_percent numeric DEFAULT 0,
    push_subscription jsonb, -- Legacy field, prefer push_subscriptions table
    role text DEFAULT 'colaborador'
);

-- 2.5 SERVICES
CREATE TABLE IF NOT EXISTS public.services (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz DEFAULT now(),
    name text NOT NULL,
    description text,
    base_price numeric DEFAULT 0,
    display_order int DEFAULT 0
);

-- 2.6 VEHICLES
CREATE TABLE IF NOT EXISTS public.vehicles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz DEFAULT now(),
    name text NOT NULL,
    description text,
    capacity text
);

-- 2.7 ORDERS
CREATE TABLE IF NOT EXISTS public.orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz DEFAULT now(),
    short_id text, -- e.g. ORD-1234
    client_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    assigned_to uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    
    status text DEFAULT 'pending', -- pending, accepted, en_camino_recoger, cargando, en_camino_entregar, completed, cancelled
    
    service_id bigint REFERENCES public.services(id),
    vehicle_id bigint REFERENCES public.vehicles(id),
    
    pickup_address text,
    pickup_lat float,
    pickup_lng float,
    
    delivery_address text,
    delivery_lat float,
    delivery_lng float,
    
    price numeric DEFAULT 0,
    distance_km numeric,
    duration_min numeric,
    
    -- Tracking & Rating
    tracking_data jsonb DEFAULT '[]'::jsonb, -- History of status changes
    rating jsonb DEFAULT '{}'::jsonb,        -- { stars: 5, comment: "..." }
    customer_comment text,                   -- Additional comment field
    completed_at timestamptz
);

-- Ensure columns exist (Idempotency for existing tables)
DO $$
BEGIN
    -- Orders: rating
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='rating') THEN
        ALTER TABLE public.orders ADD COLUMN rating jsonb DEFAULT '{}'::jsonb;
    END IF;
    -- Orders: customer_comment
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='customer_comment') THEN
        ALTER TABLE public.orders ADD COLUMN customer_comment text;
    END IF;
    -- Orders: tracking_data
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='tracking_data') THEN
        ALTER TABLE public.orders ADD COLUMN tracking_data jsonb DEFAULT '[]'::jsonb;
    END IF;
END $$;

-- ==========================================
-- 3. RLS POLICIES (DROP & CREATE)
-- ==========================================

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.push_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.business ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.collaborators ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    -- NOTIFICATIONS
    DROP POLICY IF EXISTS "Usuarios pueden ver sus propias notificaciones" ON public.notifications;
    
    -- PUSH SUBSCRIPTIONS
    DROP POLICY IF EXISTS "Usuarios pueden ver sus propias suscripciones" ON public.push_subscriptions;
    DROP POLICY IF EXISTS "Usuarios pueden registrar suscripciones" ON public.push_subscriptions;
    DROP POLICY IF EXISTS "Usuarios pueden eliminar sus suscripciones" ON public.push_subscriptions;
    
    -- BUSINESS
    DROP POLICY IF EXISTS "Publico puede ver business settings" ON public.business;
    
    -- COLLABORATORS
    DROP POLICY IF EXISTS "Publico puede ver colaboradores" ON public.collaborators;
    DROP POLICY IF EXISTS "Colaboradores pueden ver su propio perfil" ON public.collaborators;
    
    -- ORDERS
    DROP POLICY IF EXISTS "Usuarios ven sus ordenes" ON public.orders;
    DROP POLICY IF EXISTS "Colaboradores ven ordenes asignadas o pendientes" ON public.orders;
END $$;

-- Create Policies

-- Notifications
CREATE POLICY "Usuarios pueden ver sus propias notificaciones"
ON public.notifications FOR SELECT
USING (auth.uid() = user_id);

-- Push Subscriptions
CREATE POLICY "Usuarios pueden ver sus propias suscripciones"
ON public.push_subscriptions FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Usuarios pueden registrar suscripciones"
ON public.push_subscriptions FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Usuarios pueden eliminar sus suscripciones"
ON public.push_subscriptions FOR DELETE
USING (auth.uid() = user_id);

-- Business
CREATE POLICY "Publico puede ver business settings"
ON public.business FOR SELECT
USING (true);

-- Collaborators
CREATE POLICY "Publico puede ver colaboradores"
ON public.collaborators FOR SELECT
USING (true); 

-- Orders
-- Users see their own orders
CREATE POLICY "Usuarios ven sus ordenes"
ON public.orders FOR SELECT
USING (auth.uid() = client_id);

-- Collaborators see assigned orders or pending ones (simplified)
CREATE POLICY "Colaboradores ven ordenes asignadas o pendientes"
ON public.orders FOR SELECT
USING (
  assigned_to = auth.uid() 
  OR status = 'pending'
  OR exists (select 1 from public.collaborators where id = auth.uid()) -- Allow collaborators to see orders generally if needed
);

-- ==========================================
-- 4. FUNCTIONS & TRIGGERS
-- ==========================================

-- 4.1 Dispatch Notification
CREATE OR REPLACE FUNCTION public.dispatch_notification(
  p_user_id uuid,
  p_contact_id uuid,
  p_title text,
  p_body text,
  p_data jsonb
) returns void
language plpgsql
security definer
as $$
begin
  if p_user_id is null then
    return;
  end if;

  insert into public.notifications(user_id, contact_id, title, body, data)
  values (p_user_id, p_contact_id, p_title, p_body, p_data);
end;
$$;

-- 4.2 Get VAPID Key
CREATE OR REPLACE FUNCTION public.get_vapid_key()
returns text
language plpgsql
security definer
as $$
declare
  v_key text;
begin
  select vapid_public_key into v_key from public.business limit 1;
  if v_key is null then 
     select push_vapid_key into v_key from public.business limit 1;
  end if;
  return v_key;
end;
$$;

-- 4.3 Validate Active Collaborator (Used in panel-colaborador.js)
CREATE OR REPLACE FUNCTION public.validate_active_collaborator(p_user_id uuid)
returns jsonb
language plpgsql
security definer
as $$
declare
  v_status text;
begin
  select status into v_status from public.collaborators where id = p_user_id;
  if v_status = 'activo' then
    return '{"isValid": true}'::jsonb;
  else
    return '{"isValid": false}'::jsonb;
  end if;
end;
$$;

-- 4.4 Trigger Function for Orders
CREATE OR REPLACE FUNCTION public.fn_orders_notify_status()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- Si el estado cambió
  IF NEW.status <> OLD.status THEN
     -- 1. Notificar al Cliente
     IF NEW.client_id IS NOT NULL THEN
        PERFORM public.dispatch_notification(
           NEW.client_id,
           NULL, 
           'Actualización de Orden',
           'Tu orden #' || NEW.id || ' ahora está: ' || NEW.status,
           jsonb_build_object('orderId', NEW.id, 'status', NEW.status)
        );
     END IF;
     
     -- 2. Notificar al Colaborador (si está asignado)
     IF NEW.assigned_to IS NOT NULL THEN
        PERFORM public.dispatch_notification(
           NEW.assigned_to,
           NULL,
           'Orden Actualizada',
           'La orden #' || NEW.id || ' ha cambiado a: ' || NEW.status,
           jsonb_build_object('orderId', NEW.id, 'status', NEW.status)
        );
     END IF;
  END IF;
  RETURN NEW;
END;
$$;

-- 4.5 Drop/Create Trigger
DROP TRIGGER IF EXISTS trg_orders_notify_status ON public.orders;

CREATE TRIGGER trg_orders_notify_status
AFTER UPDATE ON public.orders
FOR EACH ROW
EXECUTE FUNCTION public.fn_orders_notify_status();

-- ==========================================
-- 5. INITIAL DATA
-- ==========================================

INSERT INTO public.business (id, business_name, vapid_public_key, push_vapid_key)
VALUES (
  1, 
  'Logística López Ortiz', 
  'BCgYgK3ZJwHjR529P7BaTE27ImKc6Cl-BzJSr8h2KrnUeQXth7G2iuAqfS-8BUQ9qAQ8oAMjb76cAXzA3R0MUn8',
  'BCgYgK3ZJwHjR529P7BaTE27ImKc6Cl-BzJSr8h2KrnUeQXth7G2iuAqfS-8BUQ9qAQ8oAMjb76cAXzA3R0MUn8'
)
ON CONFLICT (id) DO UPDATE
SET 
  vapid_public_key = excluded.vapid_public_key,
  push_vapid_key = excluded.push_vapid_key;
