-- 1. Create testimonials table
CREATE TABLE IF NOT EXISTS public.testimonials (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz DEFAULT now(),
    client_name text NOT NULL,
    comment text NOT NULL,
    stars int DEFAULT 5,
    is_public boolean DEFAULT true,
    display_order int DEFAULT 0,
    avatar_url text -- Optional, for future use
);

-- 2. Enable RLS
ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;

-- 3. Create Policy for Public Read
DROP POLICY IF EXISTS "Public can view testimonials" ON public.testimonials;
CREATE POLICY "Public can view testimonials"
ON public.testimonials
FOR SELECT
USING (is_public = true);

-- 4. Grant access to anon and authenticated
GRANT SELECT ON public.testimonials TO anon, authenticated;

-- 5. Create RPC function (optional, but requested by index.js logic)
CREATE OR REPLACE FUNCTION public.get_public_testimonials(limit_count int DEFAULT 10)
RETURNS SETOF public.testimonials
LANGUAGE sql
SECURITY DEFINER
AS $$
  SELECT *
  FROM public.testimonials
  WHERE is_public = true
  ORDER BY display_order ASC, created_at DESC
  LIMIT limit_count;
$$;

GRANT EXECUTE ON FUNCTION public.get_public_testimonials(int) TO anon, authenticated;

-- 6. Seed Data (Insert if empty)
INSERT INTO public.testimonials (client_name, comment, stars, display_order, created_at)
SELECT 'María González', 'Excelente servicio, llegaron súper rápido y cuidaron mis muebles.', 5, 1, now()
WHERE NOT EXISTS (SELECT 1 FROM public.testimonials);

INSERT INTO public.testimonials (client_name, comment, stars, display_order, created_at)
SELECT 'Juan Pérez', 'Muy profesionales. El seguimiento en tiempo real es una maravilla.', 5, 2, now() - interval '1 day'
WHERE NOT EXISTS (SELECT 1 FROM public.testimonials WHERE client_name = 'Juan Pérez');

INSERT INTO public.testimonials (client_name, comment, stars, display_order, created_at)
SELECT 'Empresa Logística RD', 'Hemos trabajado con ellos para carga pesada y nunca fallan.', 4, 3, now() - interval '2 days'
WHERE NOT EXISTS (SELECT 1 FROM public.testimonials WHERE client_name = 'Empresa Logística RD');

INSERT INTO public.testimonials (client_name, comment, stars, display_order, created_at)
SELECT 'Carlos Rodríguez', 'Buen precio y atención al cliente de primera.', 5, 4, now() - interval '3 days'
WHERE NOT EXISTS (SELECT 1 FROM public.testimonials WHERE client_name = 'Carlos Rodríguez');

INSERT INTO public.testimonials (client_name, comment, stars, display_order, created_at)
SELECT 'Ana Martínez', 'Me ayudaron con mi mudanza de emergencia. ¡Gracias!', 5, 5, now() - interval '4 days'
WHERE NOT EXISTS (SELECT 1 FROM public.testimonials WHERE client_name = 'Ana Martínez');
